import Head from 'next/head'
import App from './Portfolio'

export default function Home() {
  return (
    <>
      <Head>
        <title>Heddy AMARA - Front end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App />
    </>
      
  )
}
